version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  app:
    image: openjdk:22-oracle
    container_name: first_project
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./target/spring-boot-docker.jar:/spring-boot-docker.jar
    entrypoint: ["java", "-jar", "/spring-boot-docker.jar"]
    depends_on:
      - db
    networks:
      - monitoring

  db:
    image: postgres:latest
    container_name: first_project_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  postgres_data:
  grafana_data:
